travis:
  secure:
    BINSTAR_TOKEN: hW1vPXv8H9px6DrXmu6RdNnIph8roaIu6Fbzk+skSHq8ZH1/Q3CGGutIVcJJpZTwt3mrrWqEDxOyCawtO296EV8zDDmHZhLYMLLVxdGkf8o1mbakeK0Npbz2lbd9dqtgTWfV8oW1a9Puz1numaJb4x6T3dyo2YzUaY9iOZDQfu4Uw24iJmQzWlUwJkXU6Sz0efjKEiK77ll9qZMLnlj/HtpL3KdSOi1cLe3gNbF9oZv7+NegF9UcacOzVjz8KLY0U515eRkDhWNR9akmE1blh2xo80iu3pSptzZ2AqAn0eArFQYlrtC8grkNo6ufCqEhvZlzxJ6s2GcLCVIRlA69SKmzuwey/3h3J3pOwcd5Y/3ONPSGInJMn0NhRRXBGAjkzvIPDje18tWQclg8SbaXJNUX5ioSTt29dZW//oJ/gzjP3yrW2Ygo+ZVGI1iWHknTf3wGA2KomzibLxNi89io+76JQxZuQ3/H9CpLwg5+QBKPbYHq4gN3jYhYjC9FXaGfknXLo3aoFLgyWhzwp++vOkwy2mBAgEDM0r8dEwUffE3arhcNUZKbvorce0sXfgL7V3cVJQo+voyx7iJ7pbRimwmrd5EMgTtawStEPu7MUuTX4yXFVe8IvtkLiSGN9LVgeOjecvjCEgHkOUE7AZrCfLnUfP0AKFXcIlrGc2rBCus=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
